$py = "D:\App\anaconda3\python.exe"
Start-Process -WindowStyle Hidden -FilePath $py -ArgumentList "-m","sai_mcp_gis.server" -WorkingDirectory "D:\jumpingbirds\S-AI\servers\mcp-gis"
Start-Process -WindowStyle Hidden -FilePath $py -ArgumentList "-m","sai_mcp_data.server" -WorkingDirectory "D:\jumpingbirds\S-AI\servers\mcp-data"
Start-Process -WindowStyle Hidden -FilePath $py -ArgumentList "-m","sai_mcp_knowledge.server" -WorkingDirectory "D:\jumpingbirds\S-AI\servers\mcp-knowledge"
Start-Process -WindowStyle Hidden -FilePath $py -ArgumentList "-m","sai_mcp_map.server" -WorkingDirectory "D:\jumpingbirds\S-AI\servers\mcp-map"
Start-Process -WindowStyle Hidden -FilePath $py -ArgumentList "-m","sai_mcp_hydro.server" -WorkingDirectory "D:\jumpingbirds\S-AI\servers\mcp-hydro"
Start-Process -WindowStyle Hidden -FilePath $py -ArgumentList "-m","sai_mcp_flood.server" -WorkingDirectory "D:\jumpingbirds\S-AI\servers\mcp-flood"
Start-Process -WindowStyle Hidden -FilePath $py -ArgumentList "-m","sai_mcp_raster.server" -WorkingDirectory "D:\jumpingbirds\S-AI\servers\mcp-raster"
Start-Process -WindowStyle Hidden -FilePath $py -ArgumentList "web\server.py" -WorkingDirectory "D:\jumpingbirds\S-AI"
Write-Host "All 8 services launched"
